apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}
  labels:
    App: {{ .Values.serviceAccount.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      App: {{ .Values.serviceAccount.name }}
  template:
    metadata:
      labels:
        App: {{ .Values.serviceAccount.name }}
        force-recreate: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccountName: {{ include "chart-1.serviceAccountName" . }}
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "pagopa-rds-aws-secrets"
      containers:
        - name: {{ .Values.serviceAccount.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          imagePullPolicy: Always
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true

  strategy:
    type: Recreate