apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    App: {{ .Values.deployment.name }}
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: prova-aws-secrets-db, prova-aws-secrets-webuser

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      App: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        App: {{ .Values.deployment.name }}
        force-recreate: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccountName: {{ include "chart-1.serviceAccountName" . }}
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true 
          volumeAttributes:
            secretProviderClass: {{ .Values.secretProviderClass.name }}
      # - name: secrets-store-inline-2
      #   csi:
      #     driver: secrets-store.csi.k8s.io
      #     readOnly: true 
      #     volumeAttributes:
      #       secretProviderClass: {{ .Values.secretProviderClass.name }}
      containers:
        - name: {{ .Values.deployment.name }}
          env:
            - name: DATABASE_WEB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.credentialsSecretName }}
                  key: {{ .Values.database.credentialsSecretKeys.username }}
            - name: DATABASE_WEB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.credentialsSecretName }}
                  key: {{ .Values.database.credentialsSecretKeys.password }}
            - name: CAMUNDA_WEB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webuser.credentialsSecretName }}
                  key: {{ .Values.webUser.credentialsSecretKeys.username }}
            - name: CAMUNDA_WEB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webuser.credentialsSecretName }}
                  key: {{ .Values.webUser.credentialsSecretKeys.password }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          imagePullPolicy: Always
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          # - name: secrets-store-inline-2
          #   mountPath: "/mnt/secrets-store"
          #   readOnly: true

  strategy:
    type: Recreate