apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: prova-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "prova/secret"
          objectType: "secretsmanager"
          jmesPath: 
              - path: test
                objectAlias: test
              - path: provo
                objectAlias: provo
  secretObjects:
    - secretName: prova-aws-secrets  # the k8s secret name
      type: Opaque
      data:
        - objectName: "test"  # reference the corresponding parameter
          key: test
        - objectName: "provo"  # reference the corresponding parameter
          key: provo
