apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: pagopa-rds-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "pagopa-dev-atm-layer/rds/credentials"
          objectType: "secretsmanager"